export interface LawyerInt {
    firstname: string,
    lastname: string,
    birthdate: Date,
    phnno: string,
    year: string,
    address: string,
    uni: string,
    city: string,
    gender: string,
    prac: Number,
    bcn: string,
    nationality: string,
    _id?: string,
    userId: string,
    _v?: string,
    createdAt?: Date,
    updatedAt?: Date,
}